# UCV Market - Supabase Local Configuration

project_id = "ucv-market"

[api]
port = 54321
schemas = ["public", "graphql"]
extra_search_path = ["public"]

[db]
port = 54322
shadow_port = 54320

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:8100"
additional_redirect_urls = ["https://ucvmarket.pe"]
jwt_expiry = 86400 -- 24 horas

[functions]
enabled = true
